name: bmi-yaml-cpp-gtest
channels:
- conda-forge
dependencies:
- conda-forge::bmi-c
- conda-forge::bmi-cxx
- conda-forge::bmi-fortran
- conda-forge::gtest
- conda-forge::pkg-config
- conda-forge::yaml-cpp

