name: cd

on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  FORCE_COLOR: 3

permissions: {}

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: hynek/build-and-inspect-python-package@v2
